name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # 프로젝트에 맞는 Node.js 버전으로 설정

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
        run: echo "Environment variables set"

      - name: Build project
        run: npm run build

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}  # EC2_KEY 사용
        run: |
          # SSH 키 파일 생성 및 권한 설정 (확장자를 제거하여 OpenSSH 형식임을 명확히)
          echo "${EC2_KEY}" > key
          chmod 600 key
      
          # EC2 서버의 지정 경로에 빌드 파일 전송
          scp -o StrictHostKeyChecking=no -i key -r dist/* ${EC2_USER}@${EC2_HOST}:/home/ubuntu/pda_data/pda-news-frontend/
      
          # Nginx 재시작
          ssh -o StrictHostKeyChecking=no -i key ${EC2_USER}@${EC2_HOST} "sudo systemctl restart nginx"
      
          # 배포 후 키 파일 제거
          rm key
